name: KBOT-CICD

on: push

env:
  APP: "telegram-bot"
  REGISTRY: ghcr.io/${{ github.actor }}
  
  TARGET_OS: linux
  TARGET_ARCH: amd64
  
jobs:

  ci:
    name: CI
    runs-on: ubuntu-latest

    env:
      ACTIONS_RUNNER_DEBUG: true

    steps:
                          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test
      
      - name: GitHub Registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build
        run: make image APP=$APP REGISTRY=$REGISTRY TARGET_OS=$TARGET_OS TARGET_ARCH=$TARGET_ARCH
      
      - name: Push
        run: make push APP=$APP REGISTRY=$REGISTRY TARGET_ARCH=$TARGET_ARCH

